#!/bin/bash

for i in "$@"
do
case $i in

    # local build for origin/develop to tech staging
    staging)
    export OUTPUT_HOST="http://tech.phenomenonstaging.com"
    export OUTPUT_PORT=2070
    export OUTPUT_DIR="pheno-com"
    shift
    ;;

    # local build for SimpleHTTPServer
    local)
    export OUTPUT_HOST="http://localhost"
    export OUTPUT_PORT=8000
    export OUTPUT_DIR="public-staging"
    export NODE_ENV="production"
    shift
    ;;

    # local build for origin/master to latest.phenomenon.com
    latest)
    export OUTPUT_HOST="http://latest.phenomenon.com"
    export OUTPUT_PORT=80
    export OUTPUT_DIR="pheno-com"
    export NODE_ENV="production"
    shift
    ;;

    # local build for origin/master to www.phenomenon.com
    pub)
    export OUTPUT_HOST="http://www.phenomenon.com"
    export OUTPUT_PORT=80
    export OUTPUT_DIR="html"
    export NODE_ENV="production"
    shift
    ;;    

esac
shift # past argument or value
done

echo Building directory ./${OUTPUT_DIR} for ${OUTPUT_HOST}:${OUTPUT_PORT}

./node_modules/.bin/webpack --progress
